@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 22 14:58:52 +0200 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_DES_encrypt_behav -key {Behavioral:sim_1:Functional:tb_DES_encrypt} -tclbatch tb_DES_encrypt.tcl -protoinst "protoinst_files/bd_dc1c.protoinst" -protoinst "protoinst_files/tdes_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_2887.protoinst" -protoinst "protoinst_files/bd_1d12.protoinst" -protoinst "protoinst_files/bd_e989.protoinst" -protoinst "protoinst_files/desx_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_d3e0.protoinst" -protoinst "protoinst_files/des_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_277b.protoinst" -protoinst "protoinst_files/des_decrypt_bd.protoinst" -protoinst "protoinst_files/bd_b2b6.protoinst" -protoinst "protoinst_files/sdes_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_9ccb.protoinst" -log simulate.log"
call xsim  tb_DES_encrypt_behav -key {Behavioral:sim_1:Functional:tb_DES_encrypt} -tclbatch tb_DES_encrypt.tcl -protoinst "protoinst_files/bd_dc1c.protoinst" -protoinst "protoinst_files/tdes_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_2887.protoinst" -protoinst "protoinst_files/bd_1d12.protoinst" -protoinst "protoinst_files/bd_e989.protoinst" -protoinst "protoinst_files/desx_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_d3e0.protoinst" -protoinst "protoinst_files/des_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_277b.protoinst" -protoinst "protoinst_files/des_decrypt_bd.protoinst" -protoinst "protoinst_files/bd_b2b6.protoinst" -protoinst "protoinst_files/sdes_encrypt_bd.protoinst" -protoinst "protoinst_files/bd_9ccb.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
