# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/des_encrypt_bd/des_encrypt_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==des_encrypt_bd || ORIG_REF_NAME==des_encrypt_bd} -quiet] -quiet

# XDC: c:/Users/Thies/xillinx/BScThesis/BScThesis.srcs/sources_1/bd/myproj/project_1.gen/sources_1/bd/des_encrypt_bd/des_encrypt_bd_ooc.xdc
