name: Check AXI Wrappers

on:
  push:
    branches:
      - main

jobs:
  check-wrappers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate wrappers
        run: python scripts/generate_axi_wrapper.py
        
      - name: Check for differences
        run: |
          # Check if any files are different
          if git diff --quiet BScThesis.srcs/sources_1/axi_wrappers/; then
            echo "All AXI wrappers are up to date!"
            exit 0
          else
            echo "::error::AXI wrappers are out of date! Please run generate_axi_wrapper.py and commit the changes."
            echo "Changed files:"
            git diff --name-only BScThesis.srcs/sources_1/axi_wrappers/
            exit 1
          fi