name: Run VHDL Testbenches (Matrix)

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        algo: [SDES, DES, DESL, DESX, TDES, DESXL]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GHDL
        uses: ghdl/setup-ghdl@v1
        with:
          version: 5.0.1

      - name: Run Testbenches for ${{ matrix.algo }}
        run: ./scripts/test.sh ${{ matrix.algo }}